name: Fetch News Articles

on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:

jobs:
  fetch-news:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0  # Fetch all history
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      
      - name: Install dependencies
        run: |
          pip install requests python-dateutil
      
      - name: Pull latest changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git pull origin main --rebase
      
      - name: Fetch news articles
        env:
          NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
        run: |
          python fetch_news.py
      
      - name: Generate sitemap (optional)
        run: |
          if [ -f generate_sitemap.py ]; then
            python generate_sitemap.py
          else
            echo "⚠️  generate_sitemap.py not found, creating basic sitemap..."
            cat > sitemap.xml << 'EOF'
<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <url>
    <loc>https://mycitynews.ca/</loc>
    <lastmod>$(date +%Y-%m-%d)</lastmod>
    <changefreq>hourly</changefreq>
    <priority>1.0</priority>
  </url>
</urlset>
EOF
          fi
      
      - name: Check for changes
        id: changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "changed=true" >> $GITHUB_OUTPUT
            echo "✓ Changes detected"
          else
            echo "changed=false" >> $GITHUB_OUTPUT
            echo "ℹ️  No changes to commit"
          fi
      
      - name: Commit and push changes
        if: steps.changes.outputs.changed == 'true'
        run: |
          git add articles.json sitemap.xml
          git commit -m "Update news articles and sitemap [$(date +'%Y-%m-%d %H:%M:%S')]" || echo "No changes to commit"
          git pull origin main --rebase
          git push origin main
      
      - name: Summary
        if: success()
        run: |
          echo "================================"
          echo "✓ Workflow completed successfully!"
          echo "================================"
